In [23]:
#Import dependencies
import pandas as pd
import sqlite3
import argparse
import json
import pprint
import requests
import sys
import urllib
from urllib.error import HTTPError
from urllib.parse import quote
from urllib.parse import urlencode

In [24]:
#Assign database file to a variable
db_file = "Data/crimedata.db"

#Connect to database file
conn = sqlite3.connect(db_file)

In [25]:
#Query the la crime data table and put into a pandas dataframe
crime_df = pd.read_sql_query("select * from la_crime_1718;", conn)
crime_df.shape

(174766, 26)

In [26]:
#There are too many crime types to put through a model, so let's focus on only those
#crimes where there were 6,000 or more committed.  I chose 6,000 because that gives 
#us the top 11.

crime_types = pd.read_sql_query("select count(*) as cnt, CrimeCode, CrimeCodeDescription from la_crime_1718 group by CrimeCode, CrimeCodeDescription having cnt > 6000 order by cnt desc;", conn)
crime_types

      cnt CrimeCode                               CrimeCodeDescription
0   16820       624                           BATTERY - SIMPLE ASSAULT
1   14673       330                              BURGLARY FROM VEHICLE
2   13046       440                 THEFT PLAIN - PETTY ($950 & UNDER)
3   11412       510                                   VEHICLE - STOLEN
4   10286       310                                           BURGLARY
5    8903       626                  INTIMATE PARTNER - SIMPLE ASSAULT
6    8644       230     ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT
7    7344       210                                            ROBBERY
8    6942       420    THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER)
9    6670       354                                  THEFT OF IDENTITY
10   6600       745           VANDALISM - MISDEAMEANOR ($399 OR UNDER)
11   6580       740  VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...

In [34]:
#In order to train a model, it would make sense to select crimes that greatly
#vary from one another.  Using both "Burglary From Vehicle" and "Burglary"
#would probably not produce good results.  I will only keep crime types that
#I want to focus on for this exercise.

#624 = Battery-Simple Assault
#440 = Theft Plain - Petty ($950 & Under)
#510 = Vehicle - Stolen
#310 = Burglary
#740 = Vandalism-Felony

new_crime_df = pd.read_sql_query("select * from la_crime_1718 where CrimeCode in ('624', '440', '510', '310', '740');", conn)
new_crime_df.shape

(61641, 26)

In [35]:
#Query the la weather history data table and put into a pandas dataframe
weather_df = pd.read_sql_query("select * from LA_Hourly_Weather_2016_to_2018;", conn)
weather_df.head()

,dt_iso,hour,farenheit,pressure,humidity,wind_speed,weather_code,weather_main
0,1/1/2016,1,58.982,1018,22,5,800,Clear
1,1/1/2016,3,52.016,1018,21,1,800,Clear
2,1/1/2016,5,50.414,1019,34,2,800,Clear
3,1/1/2016,6,47.93,1019,32,1,800,Clear
4,1/1/2016,7,45.662,1019,32,1,721,Haze

In [36]:
#Merge the weather history with the crime data

#First, strip the first two digits of the time occured column so that we can match it up with the weather

new_crime_df['hour'] = new_crime_df['TimeOccurred'].str.slice(0,2)
new_crime_df.head()

,DRNumber,DateReported,DateOccurred,TimeOccurred,AreaID,AreaName,ReportingDistrict,CrimeCode,CrimeCodeDescription,MOCodes,...,StatusCode,StatusDescription,CrimeCode1,CrimeCode2,CrimeCode3,CrimeCode4,Address,CrossStreet,Location,hour
0,170209449,4/22/2017,4/21/2017,1930,2,Rampart,201,510,VEHICLE - STOLEN,,...,IC,Invest Cont,510,,,,ALEXANDRIA,ROMAINE,"(34.0886, -118.2979)",19
1,170206243,2/14/2017,2/11/2017,1700,2,Rampart,275,510,VEHICLE - STOLEN,,...,IC,Invest Cont,510,,,,OLYMPIC,WESTLAKE,"(34.0512, -118.2787)",17
2,170311599,4/25/2017,4/25/2017,0745,3,Southwest,325,510,VEHICLE - STOLEN,,...,IC,Invest Cont,510,,,,VERMONT,ADAMS,"(34.0328, -118.2915)",07
3,170408264,4/7/2017,4/7/2017,0001,4,Hollenbeck,421,510,VEHICLE - STOLEN,,...,IC,Invest Cont,510,,,,ALHAMBRA,VALLEY,"(34.0676, -118.2202)",00
4,170508584,4/10/2017,4/8/2017,0730,5,Harbor,566,510,VEHICLE - STOLEN,,...,IC,Invest Cont,510,,,,10TH,CENTURY,"(33.7347, -118.2842)",07

In [37]:
new_df = pd.merge(new_crime_df, weather_df, left_on=['DateOccurred', 'hour'], right_on=['dt_iso', 'hour'])
new_df.shape

(56757, 34)

In [38]:
#Drop columns from the dataframe that will not be needed in our ML models

model_df = new_df.drop(['DRNumber', 'DateReported', 'DateOccurred', 'AreaName', 'CrimeCodeDescription', 'MOCodes',
                       'PremiseDescription', 'weather_main', 'WeaponUsedCode'],
                     axis=1)
model_df

,TimeOccurred,AreaID,ReportingDistrict,CrimeCode,VictimAge,VictimSex,VictimDescent,PremiseCode,WeaponDescription,StatusCode,...,Address,CrossStreet,Location,hour,dt_iso,farenheit,pressure,humidity,wind_speed,weather_code
0,1930,2,201,510,16,,,101,,IC,...,ALEXANDRIA,ROMAINE,"(34.0886, -118.2979)",19,4/21/2017,80.492,1013,24,1,800
1,1915,1,153,440,48,F,W,502,,IC,...,500 S SPRING ST,,"(34.0467, -118.252)",19,4/21/2017,80.492,1013,24,1,800
2,1925,7,713,740,29,F,W,122,,IC,...,7500 BEVERLY BL,,"(34.0782, -118.3573)",19,4/21/2017,80.492,1013,24,1,800
3,1920,7,785,740,61,M,B,122,,IC,...,2000 S CLAUDINA AV,,"(34.0385, -118.341)",19,4/21/2017,80.492,1013,24,1,800
4,1900,8,836,310,64,F,O,502,,IC,...,10300 LA GRANGE AV,,"(34.0573, -118.4206)",19,4/21/2017,80.492,1013,24,1,800
5,1900,8,851,740,25,F,O,122,,IC,...,1500 AMHERST AV,,"(34.0395, -118.4637)",19,4/21/2017,80.492,1013,24,1,800
6,1900,9,932,440,35,F,O,108,,IC,...,6100 SEPULVEDA BL,,"(34.1806, -118.4662)",19,4/21/2017,80.492,1013,24,1,800
7,1930,9,971,440,16,F,W,210,,IC,...,15300 VENTURA BL,,"(34.1564, -118.463)",19,4/21/2017,80.492,1013,24,1,800
8,1700,2,275,510,16,,,101,,IC,...,OLYMPIC,WESTLAKE,"(34.0512, -118.2787)",17,2/11/2017,57.632,1019,87,3,500
9,1740,2,281,740,47,F,H,101,,IC,...,1200 S HOOVER ST,,"(34.0492, -118.2842)",17,2/11/2017,57.632,1019,87,3,500
10,1700,3,357,624,42,M,B,502,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",AA,...,1200 W 36TH ST,,"(34.023, -118.2944)",17,2/11/2017,57.632,1019,87,3,500
11,1700,3,395,440,20,M,H,501,,IC,...,1900 W 41ST ST,,"(34.0099, -118.3138)",17,2/11/2017,57.632,1019,87,3,500
12,1700,5,506,740,45,M,H,122,,IC,...,21800 HALLDALE AV,,"(33.8303, -118.3016)",17,2/11/2017,57.632,1019,87,3,500
13,1700,5,558,740,38,F,H,122,,IC,...,SANTA CRUZ ST,BEACON ST,"(33.7442, -118.2804)",17,2/11/2017,57.632,1019,87,3,500
14,1700,6,639,440,55,F,H,402,,IC,...,5400 HOLLYWOOD BL,,"(34.1036, -118.3049)",17,2/11/2017,57.632,1019,87,3,500
15,2300,7,727,510,16,,,101,,IC,...,LA BREA,BEVERLY,"(34.0762, -118.3441)",23,3/6/2017,61.466,1021,38,5,800
16,2300,5,515,740,,X,X,210,,IC,...,900 PCH,,"(33.7948, -118.2694)",23,3/6/2017,61.466,1021,38,5,800
17,2320,6,649,740,32,M,O,502,UNKNOWN WEAPON/OTHER WEAPON,AO,...,1600 N KINGSLEY DR,,"(34.1, -118.3033)",23,3/6/2017,61.466,1021,38,5,800
18,2340,7,711,510,16,,,108,,IC,...,400 N LA CIENEGA BL,,"(34.0784, -118.3766)",23,3/6/2017,61.466,1021,38,5,800
19,2300,7,788,740,26,M,H,108,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,...,1900 CRENSHAW BL,,"(34.0399, -118.3311)",23,3/6/2017,61.466,1021,38,5,800
20,2330,7,734,440,42,M,O,707,,IC,...,300 HAUSER BL,,"(34.0699, -118.3511)",23,3/6/2017,61.466,1021,38,5,800
21,2300,9,937,510,16,,,101,,IC,...,13700 SYLVAN ST,,"(34.1849, -118.4312)",23,3/6/2017,61.466,1021,38,5,800
22,1700,1,133,510,16,,,101,,IC,...,3RD,BROADWAY,"(34.051, -118.248)",17,5/11/2017,66.668,1021,68,5,721
23,1715,2,285,440,16,X,X,202,,IC,...,1600 W 11TH ST,,"(34.0477, -118.2751)",17,5/11/2017,66.668,1021,68,5,721
24,1700,3,395,310,75,F,B,501,,IC,...,1800 W 41ST PL,,"(34.0082, -118.3113)",17,5/11/2017,66.668,1021,68,5,721
25,1700,7,729,310,16,M,O,203,UNKNOWN WEAPON/OTHER WEAPON,IC,...,100 N LARCHMONT BL,,"(34.073, -118.3236)",17,5/11/2017,66.668,1021,68,5,721
26,1730,9,963,624,49,M,O,108,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",JO,...,5100 N SEPULVEDA BL,,"(34.1631, -118.4662)",17,5/11/2017,66.668,1021,68,5,721
27,1000,4,497,510,16,,,101,,IC,...,OLYMPIC,DACOTAH,"(34.021, -118.2123)",10,1/26/2017,42.35,1026,75,1,500
28,1000,5,502,440,57,F,B,721,,IC,...,1300 W 182ND ST,,"(33.8684, -118.2969)",10,1/26/2017,42.35,1026,75,1,500
29,1050,7,711,624,25,F,B,707,UNKNOWN WEAPON/OTHER WEAPON,IC,...,8400 BEVERLY BL,,"(34.0782, -118.3695)",10,1/26/2017,42.35,1026,75,1,500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56727,1445,7,702,624,17,M,W,101,UNKNOWN WEAPON/OTHER WEAPON,IC,...,MELROSE,SIERRA BONITA,"(34.0837, -118.3543)",14,12/16/2018,48.11,1020,79,1,500
56728,1200,7,735,624,55,F,O,203,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,...,5500 WILSHIRE BL,,"(34.0633, -118.3473)",12,12/27/2018,50.414,1014,71,0,800
56729,1200,1,166,440,35,M,B,502,,IC,...,600 S SAN PEDRO ST,,"(34.0421, -118.2469)",12,12/27/2018,50.414,1014,71,0,800
56730,1400,8,828,440,34,F,W,203,,IC,...,900 HILGARD AV,,"(34.0641, -118.4411)",14,12/18/2018,54.716,1022,93,1,500
56731,1400,3,355,440,65,M,B,501,,IC,...,3700 S GRAMERCY PL,,"(34.0208, -118.3138)",14,12/18/2018,54.716,1022,93,1,500
56732,2130,8,842,624,53,M,O,102,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,...,11700 WILSHIRE BL,,"(34.0495, -118.4609)",21,12/26/2018,63.068,1015,31,0,800
56733,2130,8,842,624,55,M,W,102,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,...,11700 WILSHIRE BL,,"(34.0495, -118.4609)",21,12/26/2018,63.068,1015,31,0,800
56734,1500,8,853,510,17,,,101,,IC,...,1500 CORINTH AV,,"(34.0478, -118.451)",15,12/29/2018,39.218,1026,41,1,800
56735,1600,8,831,310,29,M,O,502,,IC,...,11900 DOROTHY ST,,"(34.0508, -118.4683)",16,12/29/2018,40.622,1027,48,1,721
56736,1600,5,529,310,17,X,X,203,,IC,...,1000 E ANAHEIM ST,,"(33.7806, -118.2507)",16,12/29/2018,40.622,1027,48,1,721
56737,1700,8,832,440,45,M,W,502,,IC,...,1100 S BARRINGTON AV,,"(34.0511, -118.4626)",17,12/30/2018,48.758,1020,40,1,800
56738,1700,3,334,310,32,F,B,501,,IC,...,3000 S BRONSON AV,,"(34.0276, -118.3338)",17,12/30/2018,48.758,1020,40,1,800
56739,1700,4,448,510,17,,,101,,IC,...,2400 LANCASTER AV,,"(34.0592, -118.2)",17,12/30/2018,48.758,1020,40,1,800
56740,1200,9,923,624,52,F,B,502,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",AO,...,15200 VICTORY BL,,"(34.1903, -118.4574)",12,12/28/2018,48.902,1017,24,2,800
56741,1230,1,124,440,69,M,B,725,,IC,...,200 N MAIN ST,,"(34.0532, -118.2425)",12,12/28/2018,48.902,1017,24,2,800
56742,1000,1,119,440,62,F,H,900,,IC,...,800 N ALAMEDA ST,,"(34.0563, -118.2374)",10,1/4/2018,55.13,1019,93,1,721
56743,1000,1,119,440,62,F,H,900,,IC,...,800 N ALAMEDA ST,,"(34.0563, -118.2374)",10,1/4/2018,55.13,1019,93,1,500
56744,1000,1,119,440,62,F,H,900,,IC,...,800 N ALAMEDA ST,,"(34.0563, -118.2374)",10,1/4/2018,55.13,1019,93,1,721
56745,1200,3,328,740,49,M,W,122,,IC,...,800 W 32ND ST,,"(34.0248, -118.2818)",12,12/30/2018,43.016,1020,59,1,800
56746,1200,8,881,510,17,,,101,,IC,...,1800 BARRY AV,,"(34.0406, -118.4518)",12,12/30/2018,43.016,1020,59,1,800
56747,1200,5,566,310,55,F,H,501,,IC,...,200 W 13TH ST,,"(33.7324, -118.2814)",12,12/30/2018,43.016,1020,59,1,800
56748,1200,8,833,624,23,F,W,102,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,...,WESTWOOD,WILSHIRE,"(34.0578, -118.4433)",12,12/30/2018,43.016,1020,59,1,800
56749,1201,8,839,440,40,M,W,114,,IC,...,10000 W OLYMPIC BL,,"(34.0586, -118.4164)",12,12/30/2018,43.016,1020,59,1,800
56750,2005,9,904,624,65,M,W,101,STICK,IC,...,15200 LEADWELL ST,,"(34.2039, -118.464)",20,12/26/2018,62.15,1016,48,0,800
56751,2330,1,158,310,54,F,H,502,UNKNOWN WEAPON/OTHER WEAPON,IC,...,1100 E 7TH ST,,"(34.0395, -118.2405)",23,10/10/2018,72.248,1009,51,1,800
56752,1800,2,246,310,38,M,H,501,,IC,...,300 S WESTLAKE AV,,"(34.0625, -118.2714)",18,12/30/2018,53.582,1019,31,1,800
56753,1825,3,318,440,34,M,B,210,,IC,...,S VERMONT AV,W 24TH ST,"(34.0346, -118.2915)",18,12/30/2018,53.582,1019,31,1,800
56754,1515,3,378,624,47,F,H,712,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,...,3900 S FIGUEROA ST,,"(34.0146, -118.2872)",15,12/30/2018,41.558,1020,59,1,800
56755,1000,7,776,510,17,,,108,,IC,...,4600 SAINT CHARLES PL,,"(34.045, -118.3378)",10,12/27/2018,50.9,1015,64,1,800
56756,1700,13,1307,310,,M,H,203,,IC,...,700 STANFORD AV,,"(34.039, -118.2444)",17,12/28/2018,51.098,1020,16,1,800

In [39]:
model_df = model_df.drop(['WeaponDescription', 'VictimSex', 'VictimDescent', 'StatusCode', 'StatusDescription',
                         'Address', 'CrossStreet', 'CrimeCode1', 'CrimeCode2', 'CrimeCode3', 'CrimeCode4','dt_iso'], axis=1)
model_df

,TimeOccurred,AreaID,ReportingDistrict,CrimeCode,VictimAge,PremiseCode,Location,hour,farenheit,pressure,humidity,wind_speed,weather_code
0,1930,2,201,510,16,101,"(34.0886, -118.2979)",19,80.492,1013,24,1,800
1,1915,1,153,440,48,502,"(34.0467, -118.252)",19,80.492,1013,24,1,800
2,1925,7,713,740,29,122,"(34.0782, -118.3573)",19,80.492,1013,24,1,800
3,1920,7,785,740,61,122,"(34.0385, -118.341)",19,80.492,1013,24,1,800
4,1900,8,836,310,64,502,"(34.0573, -118.4206)",19,80.492,1013,24,1,800
5,1900,8,851,740,25,122,"(34.0395, -118.4637)",19,80.492,1013,24,1,800
6,1900,9,932,440,35,108,"(34.1806, -118.4662)",19,80.492,1013,24,1,800
7,1930,9,971,440,16,210,"(34.1564, -118.463)",19,80.492,1013,24,1,800
8,1700,2,275,510,16,101,"(34.0512, -118.2787)",17,57.632,1019,87,3,500
9,1740,2,281,740,47,101,"(34.0492, -118.2842)",17,57.632,1019,87,3,500
10,1700,3,357,624,42,502,"(34.023, -118.2944)",17,57.632,1019,87,3,500
11,1700,3,395,440,20,501,"(34.0099, -118.3138)",17,57.632,1019,87,3,500
12,1700,5,506,740,45,122,"(33.8303, -118.3016)",17,57.632,1019,87,3,500
13,1700,5,558,740,38,122,"(33.7442, -118.2804)",17,57.632,1019,87,3,500
14,1700,6,639,440,55,402,"(34.1036, -118.3049)",17,57.632,1019,87,3,500
15,2300,7,727,510,16,101,"(34.0762, -118.3441)",23,61.466,1021,38,5,800
16,2300,5,515,740,,210,"(33.7948, -118.2694)",23,61.466,1021,38,5,800
17,2320,6,649,740,32,502,"(34.1, -118.3033)",23,61.466,1021,38,5,800
18,2340,7,711,510,16,108,"(34.0784, -118.3766)",23,61.466,1021,38,5,800
19,2300,7,788,740,26,108,"(34.0399, -118.3311)",23,61.466,1021,38,5,800
20,2330,7,734,440,42,707,"(34.0699, -118.3511)",23,61.466,1021,38,5,800
21,2300,9,937,510,16,101,"(34.1849, -118.4312)",23,61.466,1021,38,5,800
22,1700,1,133,510,16,101,"(34.051, -118.248)",17,66.668,1021,68,5,721
23,1715,2,285,440,16,202,"(34.0477, -118.2751)",17,66.668,1021,68,5,721
24,1700,3,395,310,75,501,"(34.0082, -118.3113)",17,66.668,1021,68,5,721
25,1700,7,729,310,16,203,"(34.073, -118.3236)",17,66.668,1021,68,5,721
26,1730,9,963,624,49,108,"(34.1631, -118.4662)",17,66.668,1021,68,5,721
27,1000,4,497,510,16,101,"(34.021, -118.2123)",10,42.35,1026,75,1,500
28,1000,5,502,440,57,721,"(33.8684, -118.2969)",10,42.35,1026,75,1,500
29,1050,7,711,624,25,707,"(34.0782, -118.3695)",10,42.35,1026,75,1,500
...,...,...,...,...,...,...,...,...,...,...,...,...,...
56727,1445,7,702,624,17,101,"(34.0837, -118.3543)",14,48.11,1020,79,1,500
56728,1200,7,735,624,55,203,"(34.0633, -118.3473)",12,50.414,1014,71,0,800
56729,1200,1,166,440,35,502,"(34.0421, -118.2469)",12,50.414,1014,71,0,800
56730,1400,8,828,440,34,203,"(34.0641, -118.4411)",14,54.716,1022,93,1,500
56731,1400,3,355,440,65,501,"(34.0208, -118.3138)",14,54.716,1022,93,1,500
56732,2130,8,842,624,53,102,"(34.0495, -118.4609)",21,63.068,1015,31,0,800
56733,2130,8,842,624,55,102,"(34.0495, -118.4609)",21,63.068,1015,31,0,800
56734,1500,8,853,510,17,101,"(34.0478, -118.451)",15,39.218,1026,41,1,800
56735,1600,8,831,310,29,502,"(34.0508, -118.4683)",16,40.622,1027,48,1,721
56736,1600,5,529,310,17,203,"(33.7806, -118.2507)",16,40.622,1027,48,1,721
56737,1700,8,832,440,45,502,"(34.0511, -118.4626)",17,48.758,1020,40,1,800
56738,1700,3,334,310,32,501,"(34.0276, -118.3338)",17,48.758,1020,40,1,800
56739,1700,4,448,510,17,101,"(34.0592, -118.2)",17,48.758,1020,40,1,800
56740,1200,9,923,624,52,502,"(34.1903, -118.4574)",12,48.902,1017,24,2,800
56741,1230,1,124,440,69,725,"(34.0532, -118.2425)",12,48.902,1017,24,2,800
56742,1000,1,119,440,62,900,"(34.0563, -118.2374)",10,55.13,1019,93,1,721
56743,1000,1,119,440,62,900,"(34.0563, -118.2374)",10,55.13,1019,93,1,500
56744,1000,1,119,440,62,900,"(34.0563, -118.2374)",10,55.13,1019,93,1,721
56745,1200,3,328,740,49,122,"(34.0248, -118.2818)",12,43.016,1020,59,1,800
56746,1200,8,881,510,17,101,"(34.0406, -118.4518)",12,43.016,1020,59,1,800
56747,1200,5,566,310,55,501,"(33.7324, -118.2814)",12,43.016,1020,59,1,800
56748,1200,8,833,624,23,102,"(34.0578, -118.4433)",12,43.016,1020,59,1,800
56749,1201,8,839,440,40,114,"(34.0586, -118.4164)",12,43.016,1020,59,1,800
56750,2005,9,904,624,65,101,"(34.2039, -118.464)",20,62.15,1016,48,0,800
56751,2330,1,158,310,54,502,"(34.0395, -118.2405)",23,72.248,1009,51,1,800
56752,1800,2,246,310,38,501,"(34.0625, -118.2714)",18,53.582,1019,31,1,800
56753,1825,3,318,440,34,210,"(34.0346, -118.2915)",18,53.582,1019,31,1,800
56754,1515,3,378,624,47,712,"(34.0146, -118.2872)",15,41.558,1020,59,1,800
56755,1000,7,776,510,17,108,"(34.045, -118.3378)",10,50.9,1015,64,1,800
56756,1700,13,1307,310,,203,"(34.039, -118.2444)",17,51.098,1020,16,1,800

In [40]:
#COnvert the datatype of each column to numeric for machine learning
model_df['TimeOccurred'] = model_df['TimeOccurred'].apply(pd.to_numeric, errors='coerce')
model_df['AreaID'] = model_df['AreaID'].apply(pd.to_numeric, errors='coerce')
model_df['CrimeCode'] = model_df['CrimeCode'].apply(pd.to_numeric, errors='coerce')
model_df['ReportingDistrict'] = model_df['ReportingDistrict'].apply(pd.to_numeric, errors='coerce')
model_df['VictimAge'] = model_df['VictimAge'].apply(pd.to_numeric, errors='coerce')
model_df['PremiseCode'] = model_df['PremiseCode'].apply(pd.to_numeric, errors='coerce')
model_df['Location'] = model_df['Location'].apply(pd.to_numeric, errors='coerce')
model_df['hour'] = model_df['hour'].apply(pd.to_numeric, errors='coerce')
model_df['farenheit'] = model_df['farenheit'].apply(pd.to_numeric, errors='coerce')
model_df['pressure'] = model_df['pressure'].apply(pd.to_numeric, errors='coerce')
model_df['humidity'] = model_df['humidity'].apply(pd.to_numeric, errors='coerce')
model_df['wind_speed'] = model_df['wind_speed'].apply(pd.to_numeric, errors='coerce')
model_df['weather_code'] = model_df['weather_code'].apply(pd.to_numeric, errors='coerce')


print(model_df.dtypes)
model_df.head()

TimeOccurred           int64
AreaID                 int64
ReportingDistrict      int64
CrimeCode              int64
VictimAge            float64
PremiseCode            int64
Location             float64
hour                   int64
farenheit            float64
pressure               int64
humidity               int64
wind_speed             int64
weather_code           int64
dtype: object

,TimeOccurred,AreaID,ReportingDistrict,CrimeCode,VictimAge,PremiseCode,Location,hour,farenheit,pressure,humidity,wind_speed,weather_code
0,1930,2,201,510,16.0,101,NaN,19,80.492,1013,24,1,800
1,1915,1,153,440,48.0,502,NaN,19,80.492,1013,24,1,800
2,1925,7,713,740,29.0,122,NaN,19,80.492,1013,24,1,800
3,1920,7,785,740,61.0,122,NaN,19,80.492,1013,24,1,800
4,1900,8,836,310,64.0,502,NaN,19,80.492,1013,24,1,800

In [41]:
model_df = model_df.fillna(0)

In [42]:
model_df.reset_index()

,index,TimeOccurred,AreaID,ReportingDistrict,CrimeCode,VictimAge,PremiseCode,Location,hour,farenheit,pressure,humidity,wind_speed,weather_code
0,0,1930,2,201,510,16.0,101,0.0,19,80.492,1013,24,1,800
1,1,1915,1,153,440,48.0,502,0.0,19,80.492,1013,24,1,800
2,2,1925,7,713,740,29.0,122,0.0,19,80.492,1013,24,1,800
3,3,1920,7,785,740,61.0,122,0.0,19,80.492,1013,24,1,800
4,4,1900,8,836,310,64.0,502,0.0,19,80.492,1013,24,1,800
5,5,1900,8,851,740,25.0,122,0.0,19,80.492,1013,24,1,800
6,6,1900,9,932,440,35.0,108,0.0,19,80.492,1013,24,1,800
7,7,1930,9,971,440,16.0,210,0.0,19,80.492,1013,24,1,800
8,8,1700,2,275,510,16.0,101,0.0,17,57.632,1019,87,3,500
9,9,1740,2,281,740,47.0,101,0.0,17,57.632,1019,87,3,500
10,10,1700,3,357,624,42.0,502,0.0,17,57.632,1019,87,3,500
11,11,1700,3,395,440,20.0,501,0.0,17,57.632,1019,87,3,500
12,12,1700,5,506,740,45.0,122,0.0,17,57.632,1019,87,3,500
13,13,1700,5,558,740,38.0,122,0.0,17,57.632,1019,87,3,500
14,14,1700,6,639,440,55.0,402,0.0,17,57.632,1019,87,3,500
15,15,2300,7,727,510,16.0,101,0.0,23,61.466,1021,38,5,800
16,16,2300,5,515,740,0.0,210,0.0,23,61.466,1021,38,5,800
17,17,2320,6,649,740,32.0,502,0.0,23,61.466,1021,38,5,800
18,18,2340,7,711,510,16.0,108,0.0,23,61.466,1021,38,5,800
19,19,2300,7,788,740,26.0,108,0.0,23,61.466,1021,38,5,800
20,20,2330,7,734,440,42.0,707,0.0,23,61.466,1021,38,5,800
21,21,2300,9,937,510,16.0,101,0.0,23,61.466,1021,38,5,800
22,22,1700,1,133,510,16.0,101,0.0,17,66.668,1021,68,5,721
23,23,1715,2,285,440,16.0,202,0.0,17,66.668,1021,68,5,721
24,24,1700,3,395,310,75.0,501,0.0,17,66.668,1021,68,5,721
25,25,1700,7,729,310,16.0,203,0.0,17,66.668,1021,68,5,721
26,26,1730,9,963,624,49.0,108,0.0,17,66.668,1021,68,5,721
27,27,1000,4,497,510,16.0,101,0.0,10,42.350,1026,75,1,500
28,28,1000,5,502,440,57.0,721,0.0,10,42.350,1026,75,1,500
29,29,1050,7,711,624,25.0,707,0.0,10,42.350,1026,75,1,500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56727,56727,1445,7,702,624,17.0,101,0.0,14,48.110,1020,79,1,500
56728,56728,1200,7,735,624,55.0,203,0.0,12,50.414,1014,71,0,800
56729,56729,1200,1,166,440,35.0,502,0.0,12,50.414,1014,71,0,800
56730,56730,1400,8,828,440,34.0,203,0.0,14,54.716,1022,93,1,500
56731,56731,1400,3,355,440,65.0,501,0.0,14,54.716,1022,93,1,500
56732,56732,2130,8,842,624,53.0,102,0.0,21,63.068,1015,31,0,800
56733,56733,2130,8,842,624,55.0,102,0.0,21,63.068,1015,31,0,800
56734,56734,1500,8,853,510,17.0,101,0.0,15,39.218,1026,41,1,800
56735,56735,1600,8,831,310,29.0,502,0.0,16,40.622,1027,48,1,721
56736,56736,1600,5,529,310,17.0,203,0.0,16,40.622,1027,48,1,721
56737,56737,1700,8,832,440,45.0,502,0.0,17,48.758,1020,40,1,800
56738,56738,1700,3,334,310,32.0,501,0.0,17,48.758,1020,40,1,800
56739,56739,1700,4,448,510,17.0,101,0.0,17,48.758,1020,40,1,800
56740,56740,1200,9,923,624,52.0,502,0.0,12,48.902,1017,24,2,800
56741,56741,1230,1,124,440,69.0,725,0.0,12,48.902,1017,24,2,800
56742,56742,1000,1,119,440,62.0,900,0.0,10,55.130,1019,93,1,721
56743,56743,1000,1,119,440,62.0,900,0.0,10,55.130,1019,93,1,500
56744,56744,1000,1,119,440,62.0,900,0.0,10,55.130,1019,93,1,721
56745,56745,1200,3,328,740,49.0,122,0.0,12,43.016,1020,59,1,800
56746,56746,1200,8,881,510,17.0,101,0.0,12,43.016,1020,59,1,800
56747,56747,1200,5,566,310,55.0,501,0.0,12,43.016,1020,59,1,800
56748,56748,1200,8,833,624,23.0,102,0.0,12,43.016,1020,59,1,800
56749,56749,1201,8,839,440,40.0,114,0.0,12,43.016,1020,59,1,800
56750,56750,2005,9,904,624,65.0,101,0.0,20,62.150,1016,48,0,800
56751,56751,2330,1,158,310,54.0,502,0.0,23,72.248,1009,51,1,800
56752,56752,1800,2,246,310,38.0,501,0.0,18,53.582,1019,31,1,800
56753,56753,1825,3,318,440,34.0,210,0.0,18,53.582,1019,31,1,800
56754,56754,1515,3,378,624,47.0,712,0.0,15,41.558,1020,59,1,800
56755,56755,1000,7,776,510,17.0,108,0.0,10,50.900,1015,64,1,800
56756,56756,1700,13,1307,310,0.0,203,0.0,17,51.098,1020,16,1,800

In [43]:
# Assign X (data) and y (target) to put into model
X = model_df.drop("CrimeCode", axis=1)
y = model_df["CrimeCode"]
print(X.shape, y.shape)

(56757, 12) (56757,)

In [44]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [45]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [46]:
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [47]:
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.4539666878098057
Testing Data Score: 0.4508104298801973

In [48]:
predictions = classifier.predict(X_test)
print(f"First 10 Predictions:   {predictions[:10]}")
print(f"First 10 Actual labels: {y_test[:10].tolist()}")

First 10 Predictions:   [510 510 510 624 440 624 310 624 624 510]
First 10 Actual labels: [510, 510, 510, 440, 624, 624, 740, 440, 624, 510]

In [ ]:
#Connect to yelp API to get businesses nearby

API_KEY= "txYI2uUI8mAqa2m2ELWwZKi6d_Q9g6ndaKkGtWvjECd6IYH6uJFDaHSe0oJtbrBdLyS5WKKf1o4BxwXsDkNx16O-0bY2YydRCHzB6yBdpoLX55Fu-xU4C6bM8D2bW3Yx"

API_HOST = 'https://api.yelp.com'
SEARCH_PATH = '/v3/businesses/search'
BUSINESS_PATH = '/v3/businesses/' 

# Defaults for our simple example.
DEFAULT_TERM = 'dinner'
DEFAULT_LOCATION = 'San Francisco, CA'
SEARCH_LIMIT = 3

In [ ]:
def request(host, path, api_key, url_params=None):
    url_params = url_params or {}
    url = '{0}{1}'.format(host, quote(path.encode('utf8')))
    headers = {
        'Authorization': 'Bearer %s' % api_key,
    }

    print(u'Querying {0} ...'.format(url))

    response = requests.request('GET', url, headers=headers, params=url_params)

    return response.json()

In [ ]:
def search(api_key, term, location):
    """Query the Search API by a search term and location.
    Args:
        term (str): The search term passed to the API.
        location (str): The search location passed to the API.
    Returns:
        dict: The JSON response from the request.
    """

    url_params = {
        'term': term.replace(' ', '+'),
        'location': location.replace(' ', '+'),
        'limit': SEARCH_LIMIT
    }
    return request(API_HOST, SEARCH_PATH, api_key, url_params=url_params)

In [ ]:
def get_business(api_key, business_id):
    """Query the Business API by a business ID.
    Args:
        business_id (str): The ID of the business to query.
    Returns:
        dict: The JSON response from the request.
    """
    business_path = BUSINESS_PATH + business_id

    return request(API_HOST, business_path, api_key)

In [ ]:
def query_api(term, location):
    """Queries the API by the input values from the user.
    Args:
        term (str): The search term to query.
        location (str): The location of the business to query.
    """
    response = search(API_KEY, term, location)

    businesses = response.get('businesses')

    if not businesses:
        print(u'No businesses for {0} in {1} found.'.format(term, location))
        return

    business_id = businesses[0]['id']

    print(u'{0} businesses found, querying business info ' \
        'for the top result "{1}" ...'.format(
            len(businesses), business_id))
    response = get_business(API_KEY, business_id)

    print(u'Result for business "{0}" found:'.format(business_id))
    pprint.pprint(response, indent=2)

In [ ]:
def yelp_main():
    parser = argparse.ArgumentParser()

    parser.add_argument('-q', '--term', dest='term', default=DEFAULT_TERM,
                        type=str, help='Search term (default: %(default)s)')
    parser.add_argument('-l', '--location', dest='location',
                        default=DEFAULT_LOCATION, type=str,
                        help='Search location (default: %(default)s)')

    input_values = parser.parse_args()

    try:
        query_api(input_values.term, input_values.location)
    except HTTPError as error:
        sys.exit(
            'Encountered HTTP error {0} on {1}:\n {2}\nAbort program.'.format(
                error.code,
                error.url,
                error.read(),
            )
        )